=== fylhif/laba2/first.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/first" xmlns:sh="http://www.example.org/first"
	elementFormDefault="qualified">

	<xsd:element name="SportShop">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="sportinv" type="sh:SportInv"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:complexType name="SportInv">
		<xsd:complexContent>
			<xsd:extension base="sh:Entity">
				<xsd:all>
					<xsd:element name="name" type="xsd:string" minOccurs="1"
						maxOccurs="1" />
					<xsd:element name="company" type="xsd:string"
						minOccurs="1" maxOccurs="1" />
					<xsd:element name="description" type="sh:description"
						minOccurs="1" maxOccurs="1" />
					<xsd:element name="price" type="sh:Price" />
					<xsd:element name="category" type="sh:Category" />
					<xsd:element name="CodeTovars" minOccurs="0" maxOccurs="1"
						default="000000">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9]" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:all>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Entity" abstract="true">
		<xsd:attribute name="id" type="sh:EntityId" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="Price">
		<xsd:restriction base="xsd:decimal">
			<xsd:fractionDigits value="2" />
			<xsd:totalDigits value="5" />
			<xsd:minInclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="description">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="10" />
			<xsd:maxLength value="144" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Category">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Fitness and aerobics" />
			<xsd:enumeration value="Simulators and sports equipment" />
			<xsd:enumeration value="Game kinds of sports" />
			<xsd:enumeration value="Bicycles, electric bicycles and accessories" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="EntityId">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="-1" />
			<xsd:maxExclusive value="99999999" />
			<xsd:pattern value="[0-9]*" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== fylhif/laba2/first2.xml
<?xml version="1.0" encoding="UTF-8"?>
<sh:SportShop xmlns:sh="http://www.example.org/first" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/first first.xsd ">
  <sh:sportinv id="0">
    <sh:name>sh:name</sh:name>
    <sh:company>sh:company</sh:company>
    <sh:description>sh:description</sh:description>
    <sh:price>0.0</sh:price>
    <sh:category>Fitness and aerobics</sh:category>
    <sh:CodeTovars>000000</sh:CodeTovars>
  </sh:sportinv>
</sh:SportShop>

=== fylhif/laba2/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="goodviev.xsl"?>
<SportShop xmlns:sh="http://www.example.org/first"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/first first.xsd ">
	<order id="0">
		<name>Тренажер "Spartacus"</name>
		<company>SUPER</company>
		<description>Тренажер "Spartacus" – отличное решение для домашних
			тренировок на растяжку. Модель при правильном использовании
			выдерживает неограниченную нагрузку, не имеет ограничений по полу и
			возрасту. Длина в сложенном состоянии - 105 см.</description>
		<price>890.0</price>
		<category>Fitness and aerobics</category>
		<CodeTovars>000011</CodeTovars>
	</order>
	<order id="1">
		<name>Тренажёр для растяжки шпагата ног Triton Shpagat</name>
		<company>СУПЕR</company>
		<description>Универсальный тренажер для растяжки ног Trion. Он сделает
			ваши упражнения по растяжке простыми и приятными. Максимальный вес
			пользователя - 300 кг.</description>
		<price>837.0</price>
		<category>Fitness and aerobics</category>
		<CodeTovars>000012</CodeTovars>
	</order>
	<order id="2">
		<name>Беговая дорожка Hop-Sport электрическая HS-1402</name>
		<company>HOP-SPOT</company>
		<description>Беговая дорожка электрическая Hop-Sport HS-1402 – новинка
			среди продуктов бренда. Данная модель – идеальное решение для
			тренировок спортсменов различного уровня подготовки. Особенность
			модели – компактные габариты, стабильная конструкция, небольшой вес и
			стильный дизайн. Для комфорта пользователя предлагается 15 различных
			программ различной интенсивности и сложности. Максимальная скорость –
			16 км/ч, максимальный вес пользователя – 150 кг.</description>
		<price>20988.0</price>
		<category>Fitness and aerobics</category>
		<CodeTovars>000013</CodeTovars>
	</order>
</SportShop>

=== fylhif/laba2/jaxb.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:SportShop xmlns:sh="http://nure.ua/bookShop" xmlns:ns2="http://www.example.org/first" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/first first.xsd">
    <ns2:sportinv id="3">
        <ns2:name>Тренажер 'Spartacus'</ns2:name>
        <ns2:company>SUPER</ns2:company>
        <ns2:description>Тренажер 'Spartacus' – отличное решение для домашних тренировок на растяжку. Модель при правильном использовании выдерживает неограниченную нагрузку, не имеет ограничений по полу и возрасту. Длина в сложенном состоянии - 105 см.</ns2:description>
        <ns2:price>890.0</ns2:price>
        <ns2:category>Fitness and aerobics</ns2:category>
        <ns2:CodeTovars>000011</ns2:CodeTovars>
    </ns2:sportinv>
</ns2:SportShop>
